version: "2"
services:
  web:
    build: ./web
    volumes:
      - ./web:/web
    command: sh rundev.sh


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - "web:web"
    volumes:
      - ./conf/nginx.conf/:/etc/nginx/conf.d/
    depends_on:
      - web