# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0002_auto_20170719_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='profile',
            field=models.CharField(blank=True, choices=[('Profile A', 'Profile A'), ('Profile B', 'Profile B'), ('Profile C', 'Profile C'), ('Profile D', 'Profile D')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='humidity_by_control',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='temporature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='temporature_by_control',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
