# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0003_auto_20170721_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='profile',
            field=models.CharField(choices=[('Profile A', 'Profile A'), ('Profile B', 'Profile B'), ('Profile C', 'Profile C'), ('Profile D', 'Profile D')], default='Profile A', max_length=100, null=True),
        ),
    ]
