# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0004_auto_20170722_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='color',
            new_name='color_by_control',
        ),
        migrations.AddField(
            model_name='box',
            name='status_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
