# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0006_auto_20170726_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
