# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='nodeid',
            field=models.CharField(max_length=10),
        ),
    ]
