# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
