# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0004_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
