# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0008_auto_20170807_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box2',
            options={'ordering': ['time']},
        ),
    ]
