# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0005_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.IntegerField(default=0.0, max_length=3),
        ),
    ]
