# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0007_auto_20170807_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='humi_closelight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_closelight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='box2',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxapp.Box'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='humi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='temp',
            field=models.FloatField(default=0.0),
        ),
    ]
