# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('temporature', models.DecimalField(decimal_places=2, max_digits=15)),
                ('temporature_by_control', models.DecimalField(decimal_places=2, max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('humidity_by_control', models.DecimalField(decimal_places=2, max_digits=15)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
