# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
