# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0005_auto_20170723_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
