# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0008_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='last_name',
        ),
    ]
